In [1]:
import numpy as np


In [2]:
arr=np.array([1,2,3])

In [3]:
arr.shape

(3,)

In [4]:
arr.dtype

dtype('int32')

In [5]:
arr1=np.arange(10).reshape(5,2)

In [6]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [7]:
arr2=np.array([[1,2,3],[4,5,6]])

In [8]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr2.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [10]:
arr*2

array([2, 4, 6])

In [11]:
arr**2

array([1, 4, 9], dtype=int32)

In [12]:
arr.dtype

dtype('int32')

In [13]:
arr=np.array(arr,dtype='int64')

In [14]:
arr.dtype

dtype('int64')

In [15]:
type(arr)

numpy.ndarray

In [16]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [18]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [19]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C')
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, `None`, means
         `np.array(fill_value).dtype`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of `fill_value` with the given shape, dtype, and order.
    
    See Also
    --------
    full_like : Return a new array with shape of input filled with value.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    zeros : Return a new array setting values 

In [20]:
np.full((3,4),"*")


array([['*', '*', '*', '*'],
       ['*', '*', '*', '*'],
       ['*', '*', '*', '*']], dtype='<U1')

In [21]:
arr

array([1, 2, 3], dtype=int64)

In [22]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
np.dot(arr2,arr)

array([14, 32], dtype=int64)

In [24]:
c=np.dot(arr,arr2.T)
c

array([14, 32], dtype=int64)

In [25]:
arr.shape

(3,)

In [26]:
arr2.shape

(2, 3)

In [27]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [28]:
c.shape

(2,)

In [29]:
arr

array([1, 2, 3], dtype=int64)

In [30]:
arr3=np.array([5,6,7])

In [31]:
arr4=np.concatenate((arr,arr3),axis=0)

In [32]:
arr4

array([1, 2, 3, 5, 6, 7], dtype=int64)

In [34]:
arr4.shape

(6,)

In [39]:
arrt=arr.T

In [40]:
arr3t=arr3.T

In [43]:
arrt.shape

(3,)

In [44]:
arr5=np.concatenate((arrt,arr3t),axis=0)

In [45]:
arr5

array([1, 2, 3, 5, 6, 7], dtype=int64)

In [46]:
arr+arr3

array([ 6,  8, 10], dtype=int64)

In [48]:
arr6=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [49]:
arr6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
arr6+[1,2,3,4]

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16]])

In [51]:
arr6+np.array([1,2,3,4])

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16]])

In [52]:
arr6/10

array([[0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8],
       [0.9, 1. , 1.1, 1.2]])

In [55]:
arr6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
arr6*10

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [57]:
arr6*[1,1,1,1]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
arr6*np.array([[1],[2],[3]])

array([[ 1,  2,  3,  4],
       [10, 12, 14, 16],
       [27, 30, 33, 36]])

In [59]:
arr6+np.array([[1],[2],[3]])

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15]])

In [64]:
arr6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
arr6**0.5

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [66]:
arr6.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])