In [2]:
import numpy as np


In [3]:
arr=np.array([1,2,3])

In [4]:
arr.shape

(3,)

In [5]:
arr.dtype

dtype('int32')

In [7]:
arr1=np.arange(10).reshape(5,2)

In [8]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [9]:
arr2=np.array([[1,2,3],[4,5,6]])

In [10]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr2.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [12]:
arr*2

array([2, 4, 6])

In [13]:
arr**2

array([1, 4, 9], dtype=int32)

In [14]:
arr.dtype

dtype('int32')

In [15]:
arr=np.array(arr,dtype='int64')

In [16]:
arr.dtype

dtype('int64')

In [17]:
type(arr)

numpy.ndarray

In [18]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [21]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [24]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C')
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, `None`, means
         `np.array(fill_value).dtype`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of `fill_value` with the given shape, dtype, and order.
    
    See Also
    --------
    full_like : Return a new array with shape of input filled with value.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    zeros : Return a new array setting values 

In [27]:
np.full((3,4),"*")


array([['*', '*', '*', '*'],
       ['*', '*', '*', '*'],
       ['*', '*', '*', '*']], dtype='<U1')

In [28]:
arr

array([1, 2, 3], dtype=int64)

In [29]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
np.dot(arr2,arr)

array([14, 32], dtype=int64)

In [42]:
c=np.dot(arr,arr2.T)
c

array([14, 32], dtype=int64)

In [39]:
arr.shape

(3,)

In [40]:
arr2.shape

(2, 3)

In [41]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [43]:
c.shape

(2,)